version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: stanislavkay/postgres:13.3
    environment:
      PUBLIC_URL: "one_two"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "225567"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habrpguser -d habrdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

#    docker-compose -f local.yml up -d